server:
  port: 8084
  servlet:
    context-path: /bi
spring:
  application:
    name: bisp-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dccp?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: root
    tomcat:
      max-idle: 50
      min-idle: 5
      initial-size: 5
      max-wait: 15000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
mybatis:
  type-aliases-package: com.datacube.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: false
logging:
  level:
    root: warn
